### ISSUE TITLE
unsigned vs signed comparison in implementation

### ISSUE THREAD

**Issue by netik** [philbot9/generic-linked-list#1]
In gll.h, list->size is declared as unsigned int; In functions that manipulate the list position, these calls are signed int. This can cause issues with large lists and should be fixed.

Either make list->size signed int (which is how I fixed this in my copy of the code), or make all of the position code use unsigned int. Either way, they must be in agreement.

**Comment by philbot9** [comment]
Nice catch, thank you for this. Another example of how old code never dies :wink:.

Changing the position parameter to an unsigned int makes more sense to me since it should never be negative anyhow. Fixed in f5cd602fef7a03dd41ccdd99ec249fdf95f773f3.

**Comment by philbot9** [comment]
On second thought, I'm going to go with **signed int** everywhere. I think otherwise existing client code should be updated to use unsigned int, which isn't great.
